#AMBIENTE 
spring.profiles.active=test

# Caminho para acessar a interface gráfica do Swagger
springdoc.swagger-ui.path=/swagger-ui.html

# Caminho para acessar o JSON bruto da documentação ou seja tudo que ele espera no post/put ou entrega no get
springdoc.api-docs.path=/v3/api-docs